[package]
name = "diabot"
description = "A diabetes chat bot for Discord"
readme = "README.md"
repository = "https://github.com/cascer1/diabot"
license = "AGPL-3.0-only"
keywords = ["diabetes", "chatbot", "discord"]
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.47.1", features = ["full"] }
poise = "0.6.1"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }
dotenvy = "0.15.7"
thiserror = "2.0.17"
strum = "0.27"
strum_macros = "0.27"
reqwest = { version = "0.12", features = ["json", "gzip", "brotli", "rustls-tls"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_with = "3.15.0"
serde-query = "0.2.0"
url = "2.5.7"
chrono = "0.4.42"